### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(LQM2)
add_subdirectory(LQM2Content)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    LQM2plugin
    LQM2Contentplugin)